# Generated by Django 4.2.5 on 2023-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_cart_cartitems_cart_products_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', through='ecom_app.CartItems', to='ecom_app.products'),
        ),
    ]
